FROM oven/bun:1.1-alpine AS base

WORKDIR /app

FROM base AS install
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

FROM install AS build
COPY . .
RUN bun build apps/gateway/src/index.ts --target=bun --outdir=dist --minify

FROM base AS runner
ENV NODE_ENV=production
COPY --from=install /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json ./

EXPOSE 3000

CMD ["node", "dist/index.js"]
